[package]
name = "dominator-material-component-showcase"
version = "0.1.0"
authors = ["Mathias Myrland <jedimemo@gmail.com>"]
edition = "2018"

[profile.release]
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
dominator = "0.5.11"
dominator-material = { path = "../../" }
futures = "0.3.6"
futures-signals = "0.3.15"
futures-util = "0.3.6"
js-sys = "0.3.44"
wasm-bindgen = { ver = "0.2.67", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.18"
web-sys = { version = "0.3.4", features = ["Storage", "Url", "console", "Window", "Request", "Response", "RequestInit"] }
uuid = { version = "0.8.1", features = ["v4", "wasm-bindgen"] }
