name: Build and Deploy
on:
  push:
    tags:
      - pages.*

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: wasm-bindgen-action
        # You may pin to the exact commit or the version.
        # uses: jetli/wasm-bindgen-action@370ddd977537b33f15fd1241476a90a1254dfdae
        uses: jetli/wasm-bindgen-action@v0.1.0
        with:
          # Optional version of wasm-bindgen to install (eg. "0.2.68", "latest")
          version: 0.2.79
      - name: rust-toolchain
        # You may pin to the exact commit or the version.
        # uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
        uses: actions-rs/toolchain@v1.0.6
        with:
          # Rust toolchain name.
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: npm-action
        # You may pin to the exact commit or the version.
        # uses: jetli/trunk-action@a221e99602a4172f93fc08b44071e3f112e7df13
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install and Build 🔧
        working-directory: examples/component_showcase
        run: npm ci && npm run build
      - name: Docs
        run: cargo doc --no-deps
      - name: Populate docs
        run: mkdir pages && cp -r target/doc pages && cp -r examples/component_showcase/dist pages/examples
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: pages # The folder the action should deploy.
