name: Code checking and unit testing

on:
  push:
    branches: [ initial-code ]
  pull_request:
    branches: [ initial-code ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: wasm-bindgen-action
        # You may pin to the exact commit or the version.
        # uses: jetli/wasm-bindgen-action@370ddd977537b33f15fd1241476a90a1254dfdae
        uses: jetli/wasm-bindgen-action@v0.1.0
        with:
          # Optional version of wasm-bindgen to install (eg. "0.2.68", "latest")
          version: 0.2.87
      - name: rust-toolchain
        # You may pin to the exact commit or the version.
        # uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
        uses: actions-rs/toolchain@v1.0.6
        with:
          # Rust toolchain name.
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Run chrome tests
        run: RUST_BACKTRACE=1 CHROMEDRIVER=/usr/local/share/chrome_driver/chromedriver cargo test --target wasm32-unknown-unknown
      - name: clippy checks
        run: cargo clippy
      - name: Run unit tests
        run: cargo test
